### PR TITLE
Describe why using coroutine frame copies cannot work for postconditions

### PR DESCRIPTION
**Pull request by akrzemi1**

### CODE REVIEW

**Review by iains — COMMENTED** [review]
>It is unimplementable in the current coroutine model, where user-defined 
             promise types can choose that the coroutine is scheduled, before it initially
             suspends, to be finished asynchronously (including the destruction of the
             coroutine frame) from another thread, without any sequencing related to 
             returning from the ramp function.

It might be easier to read with the same content, but maybe some re-ordering:

"It is unimplementable in the current coroutine model, where user-defined promise types can choose that the coroutine is scheduled to be finished asynchronously (including the destruction of the coroutine frame) from another thread, before it initially
suspends, without any sequencing related to  returning from the ramp function."

(not a show-stopper either way - and we can tweak it a bit if needed.  I remain a little concerned that we are introducing multi-threading into the argument... but since Josh is confident about this model, let's proceed).

**Comment by akrzemi1** [comment]
Do you mean that this scheduling of a coroutine resumption from another thread in `await_suspend()` has never been an intended usage?

**Comment by iains** [comment]
> Do you mean that this scheduling of a coroutine resumption from another thread in `await_suspend()` has never been an intended usage?

In the case of the comment above - I only meant that it introduces another factor (multi-threading) into the discussion; I had hoped we could demonstrate that it would not work even in a single-threaded case (e.g. the self-destroy or complete-synchronously).

--- as a more general answer to the topic:

It has (AFAIK) always been an intention of folks like Lewis that this (switching between threads in await_suspend())  should work .. 
... my  personal view is that it not an ideal design scheme - because we are switching between threads while the call frame for the call to await_suspend() is on the stack (so it's not something that can be done 'indefinitely': some stack is consumed by each launched coroutine;   (IMO) a better design would be to use the handle-return version of await_suspend to resume the next coroutine as a continuation.  Of course the overall structure of the process needs to be made with that in mind - and  it could be more difficult  .. but 🤷

**Comment by akrzemi1** [comment]
> (e.g. the self-destroy or complete-synchronously).

Could you demonstrate an example of this?

Based on my sperficial knowledge of coroutines, I would think that at least the "complete-synchronously" could be comiled such that the coroutine frame is still present when evaluating the postcondition of the ramp function.

**Comment by iains** [comment]
> > (e.g. the self-destroy or complete-synchronously).
> 
> Could you demonstrate an example of this?

https://godbolt.org/z/64o34vfsa 
https://godbolt.org/z/fe36xz5Ef

> Based on my sperficial knowledge of coroutines, I would think that at least the "complete-synchronously" could be comiled such that the coroutine frame is still present when evaluating the postcondition of the ramp function.

I do not see how - if `final suspend` does not suspend (a requirement of the "finishes synchronously" statement) - then, per current wording, the coroutine state is destroyed before the ramp regains control.

FAOD: no-one is doubting that we could re-write wording to make some of these things OK - but (IMO, at least) that's heavy lifting in both the std. and the implementations.

**Pull request merged**
